# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdin.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63mdin.proto\x12\x05proto\")\n\x05Input\x12 \n\x05media\x18\x01 \x03(\x0b\x32\x11.proto.InputMedia\"\x97\x01\n\nInputMedia\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.proto.InputMedia.MediaType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"8\n\tMediaType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x45XTEND\x10\x01\x12\x08\n\x04UTF8\x10\x02\x12\x08\n\x04\x46ILE\x10\x03J\x04\x08\x04\x10\x08\x62\x06proto3'
)



_INPUTMEDIA_MEDIATYPE = _descriptor.EnumDescriptor(
  name='MediaType',
  full_name='proto.InputMedia.MediaType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTEND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UTF8', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=211,
)
_sym_db.RegisterEnumDescriptor(_INPUTMEDIA_MEDIATYPE)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='proto.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='media', full_name='proto.Input.media', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=63,
)


_INPUTMEDIA = _descriptor.Descriptor(
  name='InputMedia',
  full_name='proto.InputMedia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.InputMedia.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.InputMedia.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='proto.InputMedia.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INPUTMEDIA_MEDIATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=217,
)

_INPUT.fields_by_name['media'].message_type = _INPUTMEDIA
_INPUTMEDIA.fields_by_name['type'].enum_type = _INPUTMEDIA_MEDIATYPE
_INPUTMEDIA_MEDIATYPE.containing_type = _INPUTMEDIA
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['InputMedia'] = _INPUTMEDIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'cmdin_pb2'
  # @@protoc_insertion_point(class_scope:proto.Input)
  })
_sym_db.RegisterMessage(Input)

InputMedia = _reflection.GeneratedProtocolMessageType('InputMedia', (_message.Message,), {
  'DESCRIPTOR' : _INPUTMEDIA,
  '__module__' : 'cmdin_pb2'
  # @@protoc_insertion_point(class_scope:proto.InputMedia)
  })
_sym_db.RegisterMessage(InputMedia)


# @@protoc_insertion_point(module_scope)
