# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdout.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdout.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63mdout.proto\x12\x05proto\"%\n\x06Output\x12\x1b\n\x04msgs\x18\x01 \x03(\x0b\x32\r.proto.BotMsg\"V\n\x06\x42otMsg\x12\"\n\x06medias\x18\x01 \x03(\x0b\x32\x12.proto.OutputMedia\x12\x19\n\x11\x65mbed_recommended\x18\x02 \x01(\x08\x12\r\n\x05\x63olor\x18\x03 \x01(\r\"\xe6\x01\n\x0bOutputMedia\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.proto.OutputMedia.MediaType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x14\n\x0c\x65xtend_field\x18\x04 \x01(\x08\x12\r\n\x05level\x18\x05 \x01(\x05\x12\r\n\x05\x65rror\x18\x06 \x01(\r\x12\x0f\n\x07spoiled\x18\x07 \x01(\x08\"F\n\tMediaType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x45XTEND\x10\x01\x12\x08\n\x04UTF8\x10\x02\x12\x08\n\x04\x46ILE\x10\x03\x12\x0c\n\x08\x46ILE_URL\x10\x04\x62\x06proto3'
)



_OUTPUTMEDIA_MEDIATYPE = _descriptor.EnumDescriptor(
  name='MediaType',
  full_name='proto.OutputMedia.MediaType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTEND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UTF8', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE_URL', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=311,
  serialized_end=381,
)
_sym_db.RegisterEnumDescriptor(_OUTPUTMEDIA_MEDIATYPE)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='proto.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgs', full_name='proto.Output.msgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=60,
)


_BOTMSG = _descriptor.Descriptor(
  name='BotMsg',
  full_name='proto.BotMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='medias', full_name='proto.BotMsg.medias', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='embed_recommended', full_name='proto.BotMsg.embed_recommended', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='proto.BotMsg.color', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=148,
)


_OUTPUTMEDIA = _descriptor.Descriptor(
  name='OutputMedia',
  full_name='proto.OutputMedia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.OutputMedia.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.OutputMedia.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='proto.OutputMedia.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extend_field', full_name='proto.OutputMedia.extend_field', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='proto.OutputMedia.level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.OutputMedia.error', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spoiled', full_name='proto.OutputMedia.spoiled', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OUTPUTMEDIA_MEDIATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=381,
)

_OUTPUT.fields_by_name['msgs'].message_type = _BOTMSG
_BOTMSG.fields_by_name['medias'].message_type = _OUTPUTMEDIA
_OUTPUTMEDIA.fields_by_name['type'].enum_type = _OUTPUTMEDIA_MEDIATYPE
_OUTPUTMEDIA_MEDIATYPE.containing_type = _OUTPUTMEDIA
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['BotMsg'] = _BOTMSG
DESCRIPTOR.message_types_by_name['OutputMedia'] = _OUTPUTMEDIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'cmdout_pb2'
  # @@protoc_insertion_point(class_scope:proto.Output)
  })
_sym_db.RegisterMessage(Output)

BotMsg = _reflection.GeneratedProtocolMessageType('BotMsg', (_message.Message,), {
  'DESCRIPTOR' : _BOTMSG,
  '__module__' : 'cmdout_pb2'
  # @@protoc_insertion_point(class_scope:proto.BotMsg)
  })
_sym_db.RegisterMessage(BotMsg)

OutputMedia = _reflection.GeneratedProtocolMessageType('OutputMedia', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTMEDIA,
  '__module__' : 'cmdout_pb2'
  # @@protoc_insertion_point(class_scope:proto.OutputMedia)
  })
_sym_db.RegisterMessage(OutputMedia)


# @@protoc_insertion_point(module_scope)
