[package]
name = "prime"
version = "0.1.0"
authors = ["Amadeus_vn <git@amas.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miller_rabin = "1.0.6"
protobuf = "2.16.2"

[build-dependencies]
protoc-rust = "2.0"
