// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: botmsg.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BotMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Media:
	//	*BotMsg_Out
	//	*BotMsg_Err
	//	*BotMsg_Jpeg
	//	*BotMsg_JpegUrl
	Media isBotMsg_Media `protobuf_oneof:"media"`
}

func (x *BotMsg) Reset() {
	*x = BotMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_botmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotMsg) ProtoMessage() {}

func (x *BotMsg) ProtoReflect() protoreflect.Message {
	mi := &file_botmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotMsg.ProtoReflect.Descriptor instead.
func (*BotMsg) Descriptor() ([]byte, []int) {
	return file_botmsg_proto_rawDescGZIP(), []int{0}
}

func (m *BotMsg) GetMedia() isBotMsg_Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (x *BotMsg) GetOut() string {
	if x, ok := x.GetMedia().(*BotMsg_Out); ok {
		return x.Out
	}
	return ""
}

func (x *BotMsg) GetErr() string {
	if x, ok := x.GetMedia().(*BotMsg_Err); ok {
		return x.Err
	}
	return ""
}

func (x *BotMsg) GetJpeg() []byte {
	if x, ok := x.GetMedia().(*BotMsg_Jpeg); ok {
		return x.Jpeg
	}
	return nil
}

func (x *BotMsg) GetJpegUrl() string {
	if x, ok := x.GetMedia().(*BotMsg_JpegUrl); ok {
		return x.JpegUrl
	}
	return ""
}

type isBotMsg_Media interface {
	isBotMsg_Media()
}

type BotMsg_Out struct {
	Out string `protobuf:"bytes,1,opt,name=out,proto3,oneof"`
}

type BotMsg_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

type BotMsg_Jpeg struct {
	Jpeg []byte `protobuf:"bytes,3,opt,name=jpeg,proto3,oneof"`
}

type BotMsg_JpegUrl struct {
	JpegUrl string `protobuf:"bytes,4,opt,name=jpeg_url,json=jpegUrl,proto3,oneof"`
}

func (*BotMsg_Out) isBotMsg_Media() {}

func (*BotMsg_Err) isBotMsg_Media() {}

func (*BotMsg_Jpeg) isBotMsg_Media() {}

func (*BotMsg_JpegUrl) isBotMsg_Media() {}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*BotMsg `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_botmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_botmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_botmsg_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetMsgs() []*BotMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

var File_botmsg_proto protoreflect.FileDescriptor

var file_botmsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x12, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x6a, 0x70, 0x65, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x6a, 0x70, 0x65, 0x67, 0x12, 0x1b, 0x0a,
	0x08, 0x6a, 0x70, 0x65, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x6a, 0x70, 0x65, 0x67, 0x55, 0x72, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x22, 0x2b, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a,
	0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_botmsg_proto_rawDescOnce sync.Once
	file_botmsg_proto_rawDescData = file_botmsg_proto_rawDesc
)

func file_botmsg_proto_rawDescGZIP() []byte {
	file_botmsg_proto_rawDescOnce.Do(func() {
		file_botmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_botmsg_proto_rawDescData)
	})
	return file_botmsg_proto_rawDescData
}

var file_botmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_botmsg_proto_goTypes = []interface{}{
	(*BotMsg)(nil), // 0: proto.BotMsg
	(*Output)(nil), // 1: proto.Output
}
var file_botmsg_proto_depIdxs = []int32{
	0, // 0: proto.Output.msgs:type_name -> proto.BotMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_botmsg_proto_init() }
func file_botmsg_proto_init() {
	if File_botmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_botmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_botmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_botmsg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BotMsg_Out)(nil),
		(*BotMsg_Err)(nil),
		(*BotMsg_Jpeg)(nil),
		(*BotMsg_JpegUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_botmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_botmsg_proto_goTypes,
		DependencyIndexes: file_botmsg_proto_depIdxs,
		MessageInfos:      file_botmsg_proto_msgTypes,
	}.Build()
	File_botmsg_proto = out.File
	file_botmsg_proto_rawDesc = nil
	file_botmsg_proto_goTypes = nil
	file_botmsg_proto_depIdxs = nil
}
